"""add status fields to circle

Revision ID: 04a87faf902f
Revises: b300d687deca
Create Date: 2026-04-18 18:46:20.555740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a87faf902f'
down_revision = 'b300d687deca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quran_circles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quran_circles', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
