"""add juz_start and juz_end to surahs

Revision ID: 1bef0a6395fb
Revises: 56f692581aa3
Create Date: 2026-04-30 19:40:52.588794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bef0a6395fb'
down_revision = '56f692581aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semantic_search_logs')
    with op.batch_alter_table('verse_search_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_normalized_words'))
        batch_op.drop_index(batch_op.f('idx_search_terms'))

    op.drop_table('verse_search_index')
    op.drop_table('quran_analysis')
    op.drop_table('content_analysis_cache')
    with op.batch_alter_table('quran_verses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('surahs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('juz_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('juz_end', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surahs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('juz_end')
        batch_op.drop_column('juz_start')

    with op.batch_alter_table('quran_verses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('topic')
        batch_op.drop_column('keywords')
        batch_op.drop_column('translation')

    op.create_table('content_analysis_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('query_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('query_text', sa.TEXT(), nullable=False),
    sa.Column('analysis_result', sa.TEXT(), nullable=False),
    sa.Column('related_verses', sa.TEXT(), nullable=True),
    sa.Column('topics', sa.VARCHAR(length=500), nullable=True),
    sa.Column('hit_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_hash')
    )
    op.create_table('quran_analysis',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('verse_id', sa.INTEGER(), nullable=False),
    sa.Column('surah_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('verse_number', sa.INTEGER(), nullable=False),
    sa.Column('verse_arabic', sa.TEXT(), nullable=False),
    sa.Column('verse_persian', sa.TEXT(), nullable=False),
    sa.Column('tafsir_mukhtasar', sa.TEXT(), nullable=True),
    sa.Column('tafsir_mufassal', sa.TEXT(), nullable=True),
    sa.Column('key_concepts', sa.VARCHAR(length=500), nullable=True),
    sa.Column('thematic_tags', sa.VARCHAR(length=500), nullable=True),
    sa.Column('moral_lesson', sa.TEXT(), nullable=True),
    sa.Column('historical_context', sa.TEXT(), nullable=True),
    sa.Column('practical_application', sa.TEXT(), nullable=True),
    sa.Column('related_verses', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['verse_id'], ['quran_verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verse_search_index',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('verse_id', sa.INTEGER(), nullable=False),
    sa.Column('normalized_words', sa.TEXT(), nullable=True),
    sa.Column('search_terms', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('relevance_score', sa.FLOAT(), nullable=True),
    sa.Column('popularity_score', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['verse_id'], ['quran_verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verse_search_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_search_terms'), ['search_terms'], unique=False)
        batch_op.create_index(batch_op.f('idx_normalized_words'), ['normalized_words'], unique=False)

    op.create_table('semantic_search_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('query', sa.TEXT(), nullable=False),
    sa.Column('best_match_verse_id', sa.INTEGER(), nullable=True),
    sa.Column('match_score', sa.FLOAT(), nullable=True),
    sa.Column('match_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_clicked', sa.BOOLEAN(), nullable=True),
    sa.Column('was_helpful', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
