"""Add seraj tables

Revision ID: 33bb7589eaa0
Revises: 1fedcf41f0ba
Create Date: 2026-04-22 22:12:26.449176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bb7589eaa0'
down_revision = '1fedcf41f0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seraj_hadiths')
    op.drop_table('seraj_nahjul')
    op.drop_table('seraj_tags')
    op.drop_table('seraj_user_questions')
    op.drop_table('seraj_verses')
    op.drop_table('seraj_qa_tags')
    op.drop_table('seraj_prophets')
    with op.batch_alter_table('seraj_categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('seraj_qa', schema=None) as batch_op:
        batch_op.drop_column('answer_nahjul')
        batch_op.drop_column('answer_hadith')
        batch_op.drop_column('source_ref')
        batch_op.drop_column('answer_summary')
        batch_op.drop_column('source')
        batch_op.drop_column('primary_source')
        batch_op.drop_column('related_verses')
        batch_op.drop_column('answer_quran')
        batch_op.drop_column('related_hadiths')
        batch_op.drop_column('answer_prophets')

    with op.batch_alter_table('seraj_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seraj_suggestions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('seraj_qa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_prophets', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('related_hadiths', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('answer_quran', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('related_verses', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('primary_source', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('answer_summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('source_ref', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('answer_hadith', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('answer_nahjul', sa.TEXT(), nullable=True))

    with op.batch_alter_table('seraj_categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    op.create_table('seraj_prophets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name_arabic', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name_english', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('story', sa.TEXT(), nullable=True),
    sa.Column('miracles', sa.TEXT(), nullable=True),
    sa.Column('quran_verses', sa.TEXT(), nullable=True),
    sa.Column('hadiths', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seraj_qa_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qa_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['qa_id'], ['seraj_qa.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['seraj_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seraj_verses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('surah_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('surah_number', sa.INTEGER(), nullable=False),
    sa.Column('ayah_number', sa.INTEGER(), nullable=False),
    sa.Column('text_arabic', sa.TEXT(), nullable=False),
    sa.Column('text_persian', sa.TEXT(), nullable=False),
    sa.Column('text_english', sa.TEXT(), nullable=True),
    sa.Column('juz', sa.INTEGER(), nullable=True),
    sa.Column('page', sa.INTEGER(), nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=500), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seraj_user_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('answered_by', sa.INTEGER(), nullable=True),
    sa.Column('answered_at', sa.DATETIME(), nullable=True),
    sa.Column('vote_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['seraj_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seraj_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('seraj_nahjul',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('text_arabic', sa.TEXT(), nullable=False),
    sa.Column('text_persian', sa.TEXT(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seraj_hadiths',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text_arabic', sa.TEXT(), nullable=False),
    sa.Column('text_persian', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=False),
    sa.Column('source_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('narrator', sa.VARCHAR(length=200), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=500), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
