"""Add search models

Revision ID: 56f692581aa3
Revises: 33bb7589eaa0
Create Date: 2026-04-24 19:17:39.157066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f692581aa3'
down_revision = '33bb7589eaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sahifa_prayers')
    op.drop_table('sahifa_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sahifa_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sahifa_prayers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), nullable=False),
    sa.Column('title_arabic', sa.VARCHAR(length=300), nullable=True),
    sa.Column('occasion', sa.VARCHAR(length=200), nullable=True),
    sa.Column('arabic_text', sa.TEXT(), nullable=True),
    sa.Column('persian_text', sa.TEXT(), nullable=False),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=500), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['sahifa_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
