"""add quran ai tables

Revision ID: 5cfb20b26c5d
Revises: fa4d68e021a3
Create Date: 2026-04-19 14:23:56.343570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfb20b26c5d'
down_revision = 'fa4d68e021a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quran_qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('related_verses', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quran_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('verse_text', sa.Text(), nullable=False),
    sa.Column('verse_translation', sa.Text(), nullable=False),
    sa.Column('surah_name', sa.String(length=100), nullable=True),
    sa.Column('verse_number', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quran_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('related_verses', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quran_chats')
    op.drop_table('quran_suggestions')
    op.drop_table('quran_qa')
    # ### end Alembic commands ###
