"""make first_name and last_name nullable

Revision ID: a141261fe048
Revises: a158257788db
Create Date: 2026-04-17 19:30:33.117030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a141261fe048'
down_revision = 'a158257788db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circle_join_requests')
    op.drop_table('circle_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('professor_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('circle_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('meeting_days', sa.VARCHAR(length=200), nullable=True),
    sa.Column('meeting_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('meeting_location', sa.VARCHAR(length=300), nullable=True),
    sa.Column('duration_hours', sa.INTEGER(), nullable=True),
    sa.Column('max_members', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('admin_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circle_join_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('circle_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('motivation', sa.TEXT(), nullable=True),
    sa.Column('experience', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('admin_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['quran_circles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
